spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/trimmydb?readPreference=primary
#short_url:
#  domain: localhost:8081/
counter_file:
  location: file:${HOME}/.trimmy/counter.txt
redisson:
  address: redis://127.0.0.1:6379
  password: